import 'package:get/get.dart';

class MyTranslations implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          // TODO Boarding
          'go_to_home': 'انتقل للرئيسية',
          'boarding_title': ' استخدم التطبيق لتسهيل الوصول للأماكن التي تحتاجها في أسرع وقت. ',

          // TODO Login
          'login': 'تسجيل الدخول',
          'create_account': 'إنشاء حساب',
          'dont_have_account': 'ليس لديك حساب؟',
          'have_account': 'لدي حساب بالفعل',
          'email': 'البريد الإلكتروني',
          'username': 'إسم المستخدم',
          'profile': 'الملف الشخصي',
          'update_Profile': 'تعديل الملف الشخصي',
          'password': 'كلمة المرور',
          'confirm_password': 'تأكيد كلمة المرور',
          'enter_username': 'أدخل إسم المستخدم',
          'enter_password': 'أدخل كلمة المرور',
          'enter_confirm_password': 'أدخل تأكيد كلمة المرور',
          'validate_password': 'يجب أن تكون كلمة المرور أكثر من 6 حروف',
          'skip': 'تخطي',
          "please_login": "الرجاء تسجيل الدخول أولاً للمتابعة \n لأنك الآن في وضع الضيف",
          'ُplease_select_your_photo': 'الرجاء تحديد صورتك',
          'email_already_taken': 'البريد الإلكتروني مستخدم من قبل مستخدم أخر',

          // TODO Home
          'home': 'الرئيسية',
          'search_here': 'إبحث هنا',
          'categories': 'الأقسام',
          'places_near_you': 'الأماكن القريبة منك',
          'most_visited_places': 'الأماكن الأكثر زيارة',
          'see_more': 'رؤية المزيد',
          'go_to_map': 'انتقل للخريطة',
          'km': 'كم',
          'cities': 'المدن',

          // TODO Settings
          'settings': 'الإعدادات',
          'contact_us': 'تواصل معنا',
          'public_places': ' اضافة مكان عام',
          'Add_a_personal_place': 'اضافة مكان شخصي',
          'place': 'امكاني',
          'my_location': 'مواقعي',
          'my_current_location': 'موقعي الحالي',
          'about_us': 'معلومات عنا',
          'privacy_policy': 'سياسة الخصوصية',
          'language': 'اللغة',
          'log_out': 'تسجيل خروج',
          'cancel': 'إلغاء',
          'delete': 'حذف',
          'title_delete_place': 'حذف المكان',
          'sure_delete_place': 'هل أنت متأكد من أنك تريد حذف هذا المكان',
          'text_log_out': 'هل أنت متأكد من عملية \nالخروج من التطبيق',
          'arabic': 'العربية',
          'english': 'الإنجليزية',
          'chose_language': 'اختار اللغة',
          'problem_title': 'عنوان المشكلة',
          'enter_problem_title': 'أدخل عنوان المشكلة',
          'problem_description': 'وصف توضيحي للمشكلة',
          'enter_problem_description': 'أدخل وصف توضيحي للمشكلة',
          'send': 'إرسال',
          'about_app': 'عن التطبيق',
          'our_vision': 'رؤيتنا',
          'our_mission': 'مهمتنا',
          'our_services': 'خدماتنا',
          'add_picture': 'إضافة صورة المشكلة',
          'done_send_message': 'تم إرسال رسالتك شكرا لك',
          'category': 'القسم',
          'choose_category': 'اختر القسم',
          'choose_city': 'اختر المدينة',
          'address': 'العنوان',
          'enter_place_address': 'أدخل عنوان المكان',
          'add_place_picture': 'أضف صورة المكان',
          'place_name': 'إسم المكان',
          'place_name_en': 'إسم المكان بالإنجليزي',
          'place_description': 'وصف المكان',
          'place_description_en': 'وصف المكان بالإنجليزي',
          'enter_place_name': 'أدخل إسم المكان',
          'enter_place_name_en': 'أدخل إسم المكان بالإنجليزي',
          'enter_place_description': 'أدخل وصف المكان',
          'enter_place_description_en': 'أدخل وصف المكان بالإنجليزي',
          'done_add_place': 'تم إضافة المكان بنجاح',
          'please_pick_picture_place': 'الرجاء اختيار صورة للمكان',
          'choose_image': 'اختر صورة',
          'gallary': 'الإستديو',
          'camera': 'الكاميرا',
          'location': 'الموقع',
          'finish': 'إنهاء',
          'select_location': 'الرجاء تحديد موقع المكان من الخريطة',
          'my_places': 'أماكني',
          'phone_number': 'رقم الهاتف',
          'entre_phone_number': 'أدخل رقم الهاتف',
          'please_select_your_photo': 'الرجاء إختر صورتك الشخصية',
          'cannot_add_more_than': 'الحد المسموح به لإضافة الصورة فقط 5 صور',
          'add_place': 'أضف مكان',
          'add_personal_place': 'أضف مكانًا شخصيًا',
          'city': 'المدينة',
          'delete_place': 'تم حذف المكان',
          'no_place': 'ليس لديك أي أماكن حتى الآن',
          'google_map': 'Google Map',
          'go_to_google_map': 'اذهب إلى خريطة جوجل',
          'your_places': 'الأمكان التي قمت بأضفتها ',

        },
        "en": {
          'go_to_home': 'Go to the main',
          'boarding_title': ' Use the app to make it easy to get to the places you need in no time. ',

          // TODO Login
          'login': 'Login',
          'create_account': 'Create account',
          'email': 'E-mail',
          'dont_have_account': 'Don\'t have an account?',
          'have_account': 'I already have an account',
          'username': 'Username',
          'password': 'Password',
          'profile': 'Profile',
          'update_profile': 'Update profile',
          'enter_username': 'Enter username',
          'enter_password': 'Enter password',
          'enter_confirm_password': 'Enter confirm password',
          'confirm_password': 'Confirm password',
          'validate_password': 'Password must be more than 6 characters',
          'skip': 'Skip',
          "please_login": "Please login first to continue \nBecause you are now in guest mode",
          'ُplease_select_your_photo': 'Please select your photo',
          'email_already_taken': 'The email has already been taken',

          // TODO Home
          'home': 'Home',
          'search_here': 'Search here',
          'categories': 'Categories',
          'places_near_you': 'Places near you',
          'most_visited_places': 'Most visited places',
          'see_more': 'See More',
          'go_to_map': 'Go to the map',
          'km': 'KM',
          'update_Profile': 'Update Profial',
          'cities': 'The Cities',

          // TODO Settings
          'settings': 'Settings',
          'contact_us': 'Contact Us',
          'public_places': 'public places',
          'Add_a_personal_place': 'Add a personal place',
          'place': 'place',
          'my_location': 'My places',
          'my_current_location': 'My current location',
          'my_possibility': 'my_possibility',
          'about_us': 'About Us',
          'privacy_policy': 'Privacy Policy',
          'language': 'Language',
          'log_out': 'Log Out',
          'cancel': 'Cancel',
          'delete': 'Delete',
          'title_delete_place': 'Delete place',
          'sure_delete_place': 'Are you sure want to delete this place',
          'text_log_out': 'Are you sure about the checkout\n process  from the app',
          'arabic': 'Arabic',
          'english': 'English',
          'chose_language': 'Chose Language',
          'problem_title': 'Problem title',
          'enter_problem_title': 'Enter problem title',
          'problem_description': 'Explanation of the problem',
          'enter_problem_description': 'Enter a description of the problem',
          'send': 'Send',
          'about_app': 'About the app',
          'our_vision': 'Our vision',
          'our_mission': 'Our mission',
          'our_services': 'Our services',
          'add_picture': 'Add problem picture',
          'done_send_message': 'Your message has been sent, thank you',
          'category': 'The Category',
          'choose_category': 'Choose category',
          'choose_city': 'Choose city',
          'address': 'Address',
          'enter_place_address': 'Enter place address',
          'add_place_picture': 'Add place picture',
          'place_name': 'name of the place',
          'place_name_en': 'name of the place in english',
          'place_description': 'Description of the place',
          'place_description_en': 'Description of the place in english',
          'enter_place_name': 'Enter the place name',
          'enter_place_name_en': 'Enter the place name in english',
          'enter_place_description': 'Enter the place description',
          'enter_place_description_en': 'Enter the place description in english',
          'done_add_place': 'Done Add Place Successfully',
          'please_pick_picture_place': 'Please choose a picture of the place',
          'choose_image': 'Choose Picture',
          'gallary': 'Gallary',
          'camera': 'Camera',
          'location': 'Location',
          'finish': 'Finish',
          'select_location': 'Please select the location of the place from the map',
          'my_places': 'My Places',
          'phone_number': 'Phone number',
          'entre_phone_number': 'ُnter phone number',
          'please_select_your_photo': 'Please select your photo',
          'cannot_add_more_than': 'The limit for adding a photo is only 5 photos',
          'add_place': 'Add Place',
          'add_personal_place': 'Add personal place',
          'city': 'City',
          'delete_place': 'The place has been removed',
          'no_place': 'No have any places yet',
          'google_map': 'Google Map',
          'go_to_google_map': 'Go to google map',
          'your_places': 'The places you added',
        },
      };
}
